import { ContractInterface } from './contractInterface';

export const sepolia: ContractInterface = {
	docSchedulerAddress: '0xC94c3A55BeA20C17D51e52Fb9aaBC3BdF15d5938',
	docSchedulerAbi: [
		{
			inputs: [{ internalType: 'address', name: 'dateTimeAddress', type: 'address' }],
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [
				{ indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
				{ indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
			],
			name: 'OwnershipTransferred',
			type: 'event',
		},
		{
			inputs: [
				{
					components: [
						{ internalType: 'uint256', name: 'id', type: 'uint256' },
						{ internalType: 'uint256', name: 'startTime', type: 'uint256' },
						{ internalType: 'string', name: 'categoryName', type: 'string' },
						{ internalType: 'uint256', name: 'duration', type: 'uint256' },
						{ internalType: 'address', name: 'patient', type: 'address' },
						{ internalType: 'uint256', name: 'doctorsId', type: 'uint256' },
						{ internalType: 'uint256', name: 'reservationFee', type: 'uint256' },
					],
					internalType: 'struct DocScheduler.Appointment',
					name: 'appointment',
					type: 'tuple',
				},
			],
			name: 'createAppointment',
			outputs: [],
			stateMutability: 'payable',
			type: 'function',
		},
		{
			inputs: [
				{
					components: [
						{ internalType: 'uint256', name: 'id', type: 'uint256' },
						{ internalType: 'address', name: 'owner', type: 'address' },
						{ internalType: 'string', name: 'firstName', type: 'string' },
						{ internalType: 'string', name: 'name', type: 'string' },
						{ internalType: 'string', name: 'street', type: 'string' },
						{ internalType: 'uint256', name: 'zipCode', type: 'uint256' },
						{ internalType: 'string', name: 'city', type: 'string' },
						{ internalType: 'string', name: 'phoneNumber', type: 'string' },
						{ internalType: 'string', name: 'description', type: 'string' },
						{ internalType: 'uint256[]', name: 'openingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'closingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchStart', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchEnd', type: 'uint256[]' },
						{ internalType: 'string[]', name: 'specializations', type: 'string[]' },
						{ internalType: 'string[]', name: 'categoryNames', type: 'string[]' },
						{ internalType: 'uint256[]', name: 'categoryDurations', type: 'uint256[]' },
					],
					internalType: 'struct DocScheduler.Doctor',
					name: 'newDoctor',
					type: 'tuple',
				},
			],
			name: 'createDoctorsOffice',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'doctorId', type: 'uint256' }],
			name: 'getAppointments',
			outputs: [
				{
					components: [
						{ internalType: 'uint256', name: 'id', type: 'uint256' },
						{ internalType: 'uint256', name: 'startTime', type: 'uint256' },
						{ internalType: 'string', name: 'categoryName', type: 'string' },
						{ internalType: 'uint256', name: 'duration', type: 'uint256' },
						{ internalType: 'address', name: 'patient', type: 'address' },
						{ internalType: 'uint256', name: 'doctorsId', type: 'uint256' },
						{ internalType: 'uint256', name: 'reservationFee', type: 'uint256' },
					],
					internalType: 'struct DocScheduler.Appointment[]',
					name: '',
					type: 'tuple[]',
				},
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'startTime', type: 'uint256' }],
			name: 'getDay',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [],
			name: 'getDoctors',
			outputs: [
				{
					components: [
						{ internalType: 'uint256', name: 'id', type: 'uint256' },
						{ internalType: 'address', name: 'owner', type: 'address' },
						{ internalType: 'string', name: 'firstName', type: 'string' },
						{ internalType: 'string', name: 'name', type: 'string' },
						{ internalType: 'string', name: 'street', type: 'string' },
						{ internalType: 'uint256', name: 'zipCode', type: 'uint256' },
						{ internalType: 'string', name: 'city', type: 'string' },
						{ internalType: 'string', name: 'phoneNumber', type: 'string' },
						{ internalType: 'string', name: 'description', type: 'string' },
						{ internalType: 'uint256[]', name: 'openingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'closingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchStart', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchEnd', type: 'uint256[]' },
						{ internalType: 'string[]', name: 'specializations', type: 'string[]' },
						{ internalType: 'string[]', name: 'categoryNames', type: 'string[]' },
						{ internalType: 'uint256[]', name: 'categoryDurations', type: 'uint256[]' },
					],
					internalType: 'struct DocScheduler.Doctor[]',
					name: '',
					type: 'tuple[]',
				},
			],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'address', name: 'walletAddress', type: 'address' }],
			name: 'getPatientNameCid',
			outputs: [{ internalType: 'string', name: '', type: 'string' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [],
			name: 'getReservationFee',
			outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [],
			name: 'owner',
			outputs: [{ internalType: 'address', name: '', type: 'address' }],
			stateMutability: 'view',
			type: 'function',
		},
		{
			inputs: [
				{ internalType: 'uint256', name: 'doctorId', type: 'uint256' },
				{ internalType: 'uint256', name: 'appointmentId', type: 'uint256' },
			],
			name: 'payoutAppointment',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [
				{
					components: [
						{ internalType: 'uint256', name: 'id', type: 'uint256' },
						{ internalType: 'address', name: 'owner', type: 'address' },
						{ internalType: 'string', name: 'firstName', type: 'string' },
						{ internalType: 'string', name: 'name', type: 'string' },
						{ internalType: 'string', name: 'street', type: 'string' },
						{ internalType: 'uint256', name: 'zipCode', type: 'uint256' },
						{ internalType: 'string', name: 'city', type: 'string' },
						{ internalType: 'string', name: 'phoneNumber', type: 'string' },
						{ internalType: 'string', name: 'description', type: 'string' },
						{ internalType: 'uint256[]', name: 'openingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'closingTime', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchStart', type: 'uint256[]' },
						{ internalType: 'uint256[]', name: 'lunchEnd', type: 'uint256[]' },
						{ internalType: 'string[]', name: 'specializations', type: 'string[]' },
						{ internalType: 'string[]', name: 'categoryNames', type: 'string[]' },
						{ internalType: 'uint256[]', name: 'categoryDurations', type: 'uint256[]' },
					],
					internalType: 'struct DocScheduler.Doctor',
					name: 'doctor',
					type: 'tuple',
				},
			],
			name: 'reconfigureOffice',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'uint256', name: 'newFee', type: 'uint256' }],
			name: 'setReservationFee',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'string', name: 'cid', type: 'string' }],
			name: 'storeCid',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
			name: 'transferOwnership',
			outputs: [],
			stateMutability: 'nonpayable',
			type: 'function',
		},
	],
};
