import { Box, Button, Container, Typography, ListItem, ListItemText } from '@mui/material';
import Head from 'next/head';

import { useRouter } from 'next/router';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

export default function Home() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Ärzte ohne Grenzen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
				component="main"
				sx={{
					height: '100vh',
					position: 'relative',
					gap: '32px',
					'&::before': {
						content: '""',
						position: 'fixed',
						display: 'block',
						top: '0px',
						left: '0px',
						bottom: '0px',
						right: '0px',
						backgroundImage: 'url("/images/background.png")',
						backgroundSize: 'cover',
						backgroundRepeat: 'no-repeat',
						backgroundPosition: 'center',
						paddingBottom: '200px',
					},
				}}>
				<Container
					sx={{
						position: 'absolute',
						backgroundColor: 'rgba(255, 255, 255, 0.9)',
						width: '95%',
						height: '120vh',
						color: 'secondary.main',
						fontSize: '120%',
						padding: '2vw',
						mt: '100px',
						mb: '120px',

						transform: 'translate(2.5%, 0%)',
					}}>
					<Box sx={{ width: '80%' }}>
						<Typography variant="h2">
							Allgemeine Geschäftsbedingungen (AGB) für Ärzte ohne Grenzen
						</Typography>
						<Typography variant="body1" sx={{ mt: '12px' }}>
							Die Nutzung der Webseite zur Buchung von Arztterminen auf der Blockchain unterliegt
							den nachstehenden Allgemeinen Geschäftsbedingungen ("AGB"). Bitte lesen Sie diese
							sorgfältig durch, bevor Sie unsere Webseite nutzen.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Buchung von Arztterminen
						</Typography>
						<Typography variant="body1">
							Die Buchung von Arztterminen erfolgt über unsere Webseite auf der Blockchain. Wir
							übernehmen keine Verantwortung für die Qualität der medizinischen Leistungen, die von
							den auf unserer Webseite gelisteten Ärzten erbracht werden.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Zahlung und Stornierung
						</Typography>
						<Typography variant="body1">
							Die Bezahlung der Arzttermine erfolgt direkt an den behandelnden Arzt. Eine
							Stornierung des Termins ist nur bis zu einem bestimmten Zeitpunkt vor dem Termin
							möglich. Bitte beachten Sie hierzu die Angaben des behandelnden Arztes.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Haftungsausschluss
						</Typography>
						<Typography variant="body1">
							Ärzte ohne Grenzen übernimmt keine Haftung für die Richtigkeit, Vollständigkeit oder
							Aktualität der auf unserer Webseite zur Verfügung gestellten Informationen.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Anwendbares Recht und Gerichtsstand
						</Typography>
						<Typography variant="body1">
							Diese AGB unterliegen dem deutschen Recht. Gerichtsstand für alle Streitigkeiten, die
							sich aus diesen AGB ergeben, ist das für unseren Sitz zuständige Gericht.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Kontakt
						</Typography>
						<Typography variant="body1" component="div">
							Wenn Sie Fragen oder Bedenken hinsichtlich unserer AGB haben, kontaktieren Sie uns
							bitte unter: Ärzte ohne Grenzen Musterstraße 1 12345 Musterstadt Telefon: 0123-456789
							E-Mail: info@beispiel.de
						</Typography>
						<Typography variant="body1" sx={{ mt: '12px' }}>
							Vielen Dank für Ihr Vertrauen in Ärzte ohne Grenzen.
						</Typography>
						<Typography variant="body1" sx={{ mt: '4px' }}>
							Mit freundlichen Grüßen,
							<br />
							Das Ärzte ohne Grenzen-Team
						</Typography>
					</Box>
				</Container>
			</Box>

			<Footer />
		</>
	);
}
