import {
  Box,
  Button,
  Container,
  Typography,
  ListItem,
  ListItemText
} from '@mui/material'
import Head from 'next/head'

import { useRouter } from 'next/router'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Ärzte ohne Grenzen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box
        component="main"
        sx={{
          height: '100vh',
          position: 'relative',
          gap: '32px',
          '&::before': {
            content: '""',
            position: 'fixed',
            display: 'block',
            top: '0px',
            left: '0px',
            bottom: '0px',
            right: '0px',
            backgroundImage: 'url("/images/background.png")',
            backgroundSize: 'cover',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'center',
            paddingBottom: '200px'
          }
        }}
      >
        <Container
          sx={{
            position: 'absolute',
            backgroundColor: 'rgba(255, 255, 255, 0.9)',
            width: '95%',
            height: '120vh',
            color: 'secondary.main',
            fontSize: '120%',
            padding: '2vw',
            mt: '100px',
            mb: '120px',

            transform: 'translate(2.5%, 0%)'
          }}
        >
          <Typography variant='h2'>Datenschutz</Typography>


          {/* <Typography sx={{fontWeight: 'bold'}}>
Nutzungsdaten
</Typography>
<Typography>
Soweit erforderlich, erheben und verwenden wir sog. Nutzungsdaten von Ihnen. Dabei handelt es sich um personenbezogene Daten, die die Inanspruchnahme unseres Internetangebots sowie die Abrechnung ermöglichen. Dabei werden Daten erfasst, die sowohl die zeitlichen Kriterien der Nutzung unseres Angebots durch Sie enthalten, als auch den Umfang der Nutzung und Ihre Identifikationsmerkmale.
Wir weisen Sie darauf hin, dass es uns zu Werbezwecken, zu Zwecken der Marktforschung sowie zur Gestaltung unseres Internetangebots gestattet ist, Nutzungsprofile d.h. zusammengestellte Daten über den Verlauf von Besuchen auf unseren Seiten zu generieren. Diese Nutzungsprofile geben keinen Aufschluss über Ihre Person und werden auch nicht mit etwaigen anderen, von uns erhobenen Daten, zusammengeführt, sodass auch eine Personenidentifikation durch das Zusammenführen verschiedener Daten nicht erfolgen kann. Sie haben jederzeit das Recht, einer solchen Verwendung Ihrer Daten zu widersprechen.
</Typography>
<Typography sx={{fontWeight: 'bold'}}>
Auskunftsrecht
</Typography>
<Typography>
Wir weisen Sie darauf hin, dass Sie das Recht haben, eine Auskunft von uns über die von Ihnen gespeicherten Daten zu verlangen und im Fall der Unrichtigkeit der Daten eine Sperrung, Löschung oder Berichtigung zu veranlassen. Die Auskunftserteilung ist sowohl telefonisch als auch elektronisch möglich.
        </Typography>*/}
        </Container> 
      </Box>

      <Footer />
    </>
  )
}
