import { Box, Button, Container, Typography, ListItem, ListItemText } from '@mui/material';
import Head from 'next/head';

import { useRouter } from 'next/router';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

export default function Home() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Ärzte ohne Grenzen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
				component="main"
				sx={{
					height: '100vh',
					position: 'relative',
					gap: '32px',
					'&::before': {
						content: '""',
						position: 'fixed',
						display: 'block',
						top: '0px',
						left: '0px',
						bottom: '0px',
						right: '0px',
						backgroundImage: 'url("/images/background.png")',
						backgroundSize: 'cover',
						backgroundRepeat: 'no-repeat',
						backgroundPosition: 'center',
						paddingBottom: '200px',
					},
				}}>
				<Container
					sx={{
						position: 'absolute',
						backgroundColor: 'rgba(255, 255, 255, 0.9)',
						width: '95%',
						height: '120vh',
						color: 'secondary.main',
						fontSize: '120%',
						padding: '2vw',
						mt: '100px',
						mb: '120px',

						transform: 'translate(2.5%, 0%)',
					}}>
					<Box sx={{ width: '80%' }}>
						<Typography variant="h2">Datenschutzrichtlinie für Ärzte ohne Grenzen</Typography>
						<Typography variant="body1">
							Diese Datenschutzrichtlinie beschreibt, wie Ärzte ohne Grenzen personenbezogene Daten
							erhebt, verarbeitet, speichert und teilt, die im Zusammenhang mit der Nutzung unserer
							Webseite zur Buchung von Arztterminen auf der Blockchain stehen.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Erhebung von Daten
						</Typography>
						<Typography variant="body1">
							Wir erheben personenbezogene Daten wie Name, Adresse, Telefonnummer und E-Mail-Adresse
							von Benutzern, die unsere Webseite nutzen, um einen Arzttermin zu buchen. Wir erheben
							auch Informationen über den Zweck des Arzttermins, um sicherzustellen, dass der
							Benutzer den am besten geeigneten Arzt findet.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Verarbeitung von Daten
						</Typography>
						<Typography variant="body1">
							Die von uns erhobenen personenbezogenen Daten werden von uns ausschließlich für den
							Zweck der Buchung von Arztterminen verwendet. Wir werden Ihre Daten niemals ohne Ihre
							ausdrückliche Zustimmung an Dritte weitergeben oder verkaufen.
						</Typography>
						<Typography variant="body1">Speicherung von Daten</Typography>
						<Typography variant="body1">
							Wir speichern personenbezogene Daten nur so lange, wie es für den Zweck der Buchung
							von Arztterminen notwendig ist. Wir ergreifen alle notwendigen technischen und
							organisatorischen Maßnahmen, um sicherzustellen, dass Ihre Daten sicher aufbewahrt
							werden.
						</Typography>
						<Typography variant="body1">Teilen von Daten</Typography>
						<Typography variant="body1">
							Wir teilen personenbezogene Daten nur mit autorisierten Dritten, die an der Buchung
							von Arztterminen beteiligt sind, wie z.B. Ärzten und Kliniken. Wir stellen sicher,
							dass diese Dritten Ihre Daten nur für den Zweck der Buchung von Arztterminen verwenden
							und dass sie alle notwendigen Datenschutzmaßnahmen ergreifen.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Ihre Rechte
						</Typography>
						<Typography variant="body1">
							Sie haben das Recht, auf Ihre personenbezogenen Daten zuzugreifen, sie zu korrigieren
							oder zu löschen. Sie haben auch das Recht, der Verarbeitung Ihrer Daten zu
							widersprechen oder eine Einschränkung der Verarbeitung zu verlangen. Wenn Sie Fragen
							zu Ihren Rechten haben, kontaktieren Sie uns bitte unter den unten angegebenen
							Kontaktdaten.
						</Typography>
						<Typography variant="h3" sx={{ mt: '16px' }}>
							Kontakt
						</Typography>
						<Typography variant="body1">
							Wenn Sie Fragen oder Bedenken hinsichtlich unserer Datenschutzrichtlinie haben,
							kontaktieren Sie uns bitte unter:
						</Typography>
						<Typography variant="body2" sx={{ mt: '12px' }}>
							Ärzte ohne Grenzen <br /> Musterstraße 1 <br /> 12345 Musterstadt <br /> Telefon:
							0123-456789 <br /> E-Mail: info@beispiel.de
						</Typography>
						<Typography variant="body2" sx={{ mt: '12px' }}>
							Vielen Dank für Ihr Vertrauen in Ärzte ohne Grenzen.
						</Typography>
						<Typography variant="body2" sx={{ mt: '4px' }}>
							Mit freundlichen Grüßen,
							<br />
							Das Ärzte ohne Grenzen-Team
						</Typography>
					</Box>
				</Container>
			</Box>

			<Footer />
		</>
	);
}
