import { Box, InputBase, styled, TextField, Typography } from '@mui/material';
import Head from 'next/head';
import { useRouter } from 'next/router';
import DoctorCard from '../components/DoctorCard/DoctorCard';
import Navbar from '../components/Navbar/Navbar';

export default function Home() {
	const router = useRouter();
	const { zipCode, areaOfExpertise } = router.query;

	return (
		<>
			<Head>
				<title>Ärzte ohne Grenzen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
				component="main"
				sx={{
					display: 'flex',
					flexDirection: 'column',
					alignItems: 'center',
					width: '100vw',
					mt: '70px',
				}}>
				{/* <Typography variant="h2">{zipCode}</Typography>
				<Typography variant="h2">{areaOfExpertise}</Typography> */}
				<Box
					sx={{
						display: 'grid',
						gridTemplateColumns: 'auto auto',
						gap: '24px',
						p: '24px',
					}}>
					<DoctorCard
						doctor={{
							name: 'Doktor MegaGut',
							address: 'Bahnhofstraße 1',
							zipCode: 90441,
							city: 'Nuernberg',
							openHours: [{ start: 8.3 * 60 * 60 * 1000, end: 16 * 60 * 60 * 1000 }],
						}}
					/>
					<DoctorCard
						doctor={{
							name: 'Doktor MegaGut',
							address: 'Bahnhofstraße 1',
							zipCode: 90441,
							city: 'Nuernberg',
							openHours: [{ start: 8.3 * 60 * 60 * 1000, end: 16 * 60 * 60 * 1000 }],
						}}
					/>
					<DoctorCard
						doctor={{
							name: 'Doktor MegaGut',
							address: 'Bahnhofstraße 1',
							zipCode: 90441,
							city: 'Nuernberg',
							openHours: [{ start: 8.3 * 60 * 60 * 1000, end: 16 * 60 * 60 * 1000 }],
						}}
					/>
					<DoctorCard
						doctor={{
							name: 'Doktor MegaGut',
							address: 'Bahnhofstraße 1',
							zipCode: 90441,
							city: 'Nuernberg',
							openHours: [{ start: 8.3 * 60 * 60 * 1000, end: 16 * 60 * 60 * 1000 }],
						}}
					/>
				</Box>
			</Box>
		</>
	);
}
