import {
	Box,
	Button,
	Container,
	Typography,
    ListItem,
    ListItemText,
    
} from '@mui/material';
import Head from 'next/head';

import { useRouter } from 'next/router';
import { FAQ, faqsAerzte } from '../constants/faqs';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';
import { List } from '@mui/icons-material';


export default function Home() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Ärzte ohne Grenzen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
            component="main"
            sx={{
                //position: 'relative',
                //display: 'flex',
                //flexDirection: 'column',
                // alignItems: 'center',
                // justifyContent: 'center',
                //minHeight: '900px', // nicht notwendig, wird mit 100vh auf jeweilige Hoehe skaliert
                height: '100vh',
                //py: '256px', // nicht mehr notwendig
                backgroundImage: 'url("/images/background.png")',
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                gap: '32px',
            
            }}>
            
            <Container sx={{
                position: 'fixed',
                backgroundColor: 'rgba(255, 255, 255, 0.9)',
                width: '95%',
                color: 'secondary.main',
                fontSize: '120%',
                padding: '2vw',
                mt: '80px',
                
                transform: 'translate(2.5%, 10%)',
            }}>

            
            
                FAQs - Ärzte
                
                {faqsAerzte.map((item, index) => (
                    <ListItem sx={{padding: '10px'}}>
                        <ListItemText
                        
                        secondaryTypographyProps={{ sx: { color: "secondary.main", fontSize: '70%'  }}}
                        primaryTypographyProps={ {sx: {color: '#A7BDA6', fontSize: '80%', fontWeight: 'bolder'}}}
                        key={index}
                        sx={{fontSize:'120%', wontWeight:'1000'}}
                        primary={"Frage: " + item.question}
                        secondary={'Antwort: ' + item.answer}
                        />
                    </ListItem>
                        
                    
                ))}
            
            </Container>

            </Box>
            
			<Footer />
		</>
	);
}