import {
  Box,
  Button,
  Container,
  Typography,
  ListItem,
  ListItemText
} from '@mui/material'
import Head from 'next/head'

import { useRouter } from 'next/router'
import { FAQ, faqsAerzte } from '../constants/faqs'
import Navbar from '../components/Navbar/Navbar'
import Footer from '../components/Footer/Footer'
import { List } from '@mui/icons-material'

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Ärzte ohne Grenzen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box
        component="main"
        sx={{
          height: '100vh',
          position: 'relative',
          gap: '32px',
          '&::before': {
            content: '""',
            position: 'fixed',
            display: 'block',
            top: '0px',
            left: '0px',
            bottom: '0px',
            right: '0px',
            backgroundImage: 'url("/images/background.png")',
            backgroundSize: 'cover',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'center',
            paddingBottom: '200px'
          }
        }}
      >
        <Container
          sx={{
            position: 'absolute',
            backgroundColor: 'rgba(255, 255, 255, 0.9)',
            width: '95%',
            color: 'secondary.main',
            fontSize: '120%',
            padding: '2vw',
            mt: '100px',
						mb: '120px',
						transform: 'translate(2.5%, 0%)',
						display: 'flex',
						flexDirection: 'column',
            // gap: '15px',
          }}
        >
         <Typography variant='h2'>FAQs Ärzte</Typography>
          {faqsAerzte.map((item, index) => (
            <ListItem sx={{ padding: '10px' }}>
              <ListItemText
                secondaryTypographyProps={{
                  sx: { color: 'secondary.main', fontSize: '70%' }
                }}
                primaryTypographyProps={{
                  sx: {
                    color: '#A7BDA6',
                    fontSize: '80%',
                    fontWeight: 'bolder'
                  }
                }}
                key={index}
                sx={{ fontSize: '120%', wontWeight: '1000' }}
                primary={'Frage: ' + item.question}
                secondary={'Antwort: ' + item.answer}
              />
            </ListItem>
          ))}
        </Container>
      </Box>

      <Footer />
    </>
  )
}
