import {
	Box,
	Button,
	Container,
	Typography,
    ListItem,
    ListItemText,
    
} from '@mui/material';
import Head from 'next/head';

import { useRouter } from 'next/router';
import Navbar from '../components/Navbar/Navbar';
import Footer from '../components/Footer/Footer';

export default function Home() {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Ärzte ohne Grenzen</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
                component="main"
                sx={{
                    
                    height: '100vh',
                    position: 'relative',
                    gap: '32px',
                    '&::before': {
                        content: '""',
                        position:'fixed',
                        display:'block',
                        top: '0px',
                        left: '0px',
                        bottom: '0px',
                        right: '0px',
                        backgroundImage: 'url("/images/background.png")',
                        backgroundSize: 'cover',
                        backgroundRepeat: 'no-repeat',
                        backgroundPosition: 'center',
                        paddingBottom: '200px',
                      }
                
                }}
            >
                
                <Container 
                    sx={{
                        position: 'absolute',
                        backgroundColor: 'rgba(255, 255, 255, 0.9)',
                        width: '95%',
                        height: '120vh',
                        color: 'secondary.main',
                        fontSize: '120%',
                        padding: '2vw',
                        mt: '100px',
                        mb: '120px',
                        
                        transform: 'translate(2.5%, 0%)',
                    }}
                >
                    Impressum
                    
                </Container>

            </Box>
            
			<Footer />
		</>
	);
}